# Generated by Django 5.2.7 on 2025-10-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekartApp', '0003_kart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
